require("config.autocmds.buffer")
require("config.autocmds.cmdline")
require("config.autocmds.custom")
require("config.autocmds.terminal")
require("config.autocmds.window")
require("config.autocmds.yank")
