# Application bindings
bindd = SUPER, RETURN, Tmux, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)" tmux new -A -s dotfiles -c ~/dotfiles
bind = , F8, pass, class:^(com\.obsproject\.Studio)$
bind = , F7, pass, class:^(com\.obsproject\.Studio)$
bind = SUPER CTRL, P, pin

$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

unbind = SUPER D
bindd = SUPER, D, Dictate, exec, voxtype record start
bindrd = SUPER, D, Dictate, exec, voxtype record stop
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, T, Activity, exec, omarchy-launch-tui btop
bindd = SUPER, L, Switch Languages, exec, hyprctl switchxkblayout at-translated-set-2-keyboard next
bindd = SUPER, F1, Lower Brightness, exec, brightnessctl set 1%-
bindd = SUPER, F2, Higher Brightness, exec, brightnessctl set 1%+

bindd = SUPER, Y, Switch to workspace 1, workspace, 1
bindd = SUPER, U, Switch to workspace 2, workspace, 2
bindd = SUPER, I, Switch to workspace 3, workspace, 3
unbind = SUPER, O
bindd = SUPER, O, Switch to workspace 4, workspace, 4
unbind = SUPER, P
bindd = SUPER, P, Switch to workspace 5, workspace, 5
bindd = SUPER SHIFT, Y, Move window to workspace 1, movetoworkspace, 1
bindd = SUPER SHIFT, U, Move window to workspace 2, movetoworkspace, 2
bindd = SUPER SHIFT, I, Move window to workspace 3, movetoworkspace, 3
unbind = SUPER SHIFT, O
bindd = SUPER SHIFT, O, Move window to workspace 4, movetoworkspace, 4
unbind = SUPER SHIFT, P
bindd = SUPER SHIFT, P, Move window to workspace 5, movetoworkspace, 5
# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
