require("config.options")
require("config.keymaps")
require("config.autocmds")
require("config.session")
require("config.tabs")

require("plugins.theme")
require("plugins.treesitter")
require("plugins.oil")
require("plugins.lsp")
require("plugins.coding")
require("plugins.cmp")
require("plugins.markdown")
