require("config.options")
require("config.keymaps")
require("config.autocmds")
require("config.lazy")
require("config.general")
require("config.overrides")
require("config.tabs")
require("config.log").setup(vim.log.levels.INFO)
